# Generated by Django 6.1 on 2026-08-15 18:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Tashkilot nomi')),
                ('org_type', models.CharField(choices=[('xususiy_kasalxona', 'Xususiy kasalxona'), ('davlat_shifoxonasi', 'Davlat shifoxonasi'), ('dorixona', 'Dorixona'), ('kafe', 'Kafe'), ('restoran', 'Restoran'), ('muzey', 'Muzey'), ('teatr', 'Teatr'), ('maktab', 'Maktab'), ('oliy_talim', "Oliy ta'lim muassasasi"), ('bank', 'Bank'), ('bogcha', "Bog'cha"), ('boshqa', 'Boshqa')], max_length=50, verbose_name='Tashkilot turi')),
                ('address', models.TextField(verbose_name='Manzili')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Fikr va mulohaza')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='organizations.organization')),
            ],
        ),
    ]
