# Generated by Django 5.2.17 on 2026-08-16 09:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('xodimlar', "Xodimlar va xizmat ko'rsatish"), ('sharoit', "Texnik ta'minot va sharoitlar"), ('tibbiy', 'Tibbiy xizmat va dori-darmon'), ('moliyaviy', 'Moliyaviy masalalar va narxlar'), ('boshqa', 'Boshqa masalalar')], db_index=True, default='boshqa', max_length=20, verbose_name='Toifa'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='submitter_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('xususiy_kasalxona', 'Xususiy kasalxona'), ('davlat_shifoxonasi', 'Davlat shifoxonasi'), ('xususiy_klinika', 'Xususiy klinika')], max_length=50, verbose_name='Tashkilot turi'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=32, verbose_name='Xona raqami')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name="Bo'lim yoki izoh")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='organizations.organization')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('organization', 'number')},
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='organizations.room'),
        ),
    ]
