# Generated by Django 5.2.17 on 2026-08-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_feedback_options_feedback_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feedback/', verbose_name='Rasm'),
        ),
    ]
