# Generated by Django 6.1 on 2026-08-17 07:32

import django.db.models.deletion
from django.db import migrations, models


def rasmlarni_kochirish(apps, schema_editor):
    """Feedback.image dagi mavjud rasmlarni FeedbackImage ga ko'chiradi.

    Eski model bitta rasm saqlar edi. Fayllarning o'ziga tegilmaydi —
    ular saqlash joyida (R2 yoki lokal disk) o'z o'rnida qoladi, faqat
    bog'lanish yangi jadvalga ko'chiriladi. Feedback.image qiymati ham
    o'chirilmaydi, shunda migratsiyani orqaga qaytarish xavfsiz bo'ladi.
    """
    Feedback = apps.get_model('organizations', 'Feedback')
    FeedbackImage = apps.get_model('organizations', 'FeedbackImage')

    for fikr in Feedback.objects.exclude(image='').exclude(image=None):
        FeedbackImage.objects.create(feedback=fikr, image=fikr.image.name)


def kochirishni_bekor_qilish(apps, schema_editor):
    """Orqaga qaytarish. Feedback.image daxlsiz qolgani uchun rasmlar
    yo'qolmaydi, faqat yangi jadvaldagi yozuvlar o'chadi."""
    FeedbackImage = apps.get_model('organizations', 'FeedbackImage')
    FeedbackImage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_feedback_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='feedback/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='organizations.feedback')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.RunPython(rasmlarni_kochirish, kochirishni_bekor_qilish),
    ]
