# Generated by Django 6.1 on 2026-08-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_feedbackimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='classified_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Toifalangan vaqt'),
        ),
    ]
